project:
  type: book
  
number-depth: 3
number-sections: true

filters:
   - include-code-files

book:
  title: "Applying the Management Strategy Evaluation tool `{openMSE}` to the Antarctic Krill fishery case"
  author: Bruno Caneco
  date: today
  chapters: 
    - index.qmd
    - part: part1_openMSE_GRYM_approx/part1.qmd
      chapters: 
        - part1_openMSE_GRYM_approx/1_RecCV_and_M/generate_RCV_and_M.qmd
        - part1_openMSE_GRYM_approx/2_GRYM_sims/grym_sims.qmd
        - part1_openMSE_GRYM_approx/3_openMSE_sims/openmse_sims.qmd
        - part1_openMSE_GRYM_approx/5_appendices/krill_om_report_example.qmd
    - part: "MSE application"
    - references.qmd

format:
  html:
    theme: lumen
    df-print: paged
    fontsize: 1.1em
    fig-cap-location: top
    callout-appearance: simple
    comments:
      hypothesis: true
    
editor: source

bibliography: references.json
#csl: fishres.csl
nocite: |
 @maschette_etal21, @thanassekos_etal21, @constable_delamare96, @sc-camlr00, @kawaguchi16
